// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shielf.Data;

#nullable disable

namespace Shielf.Migrations
{
    [DbContext(typeof(ShielfContext))]
    partial class ShielfContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Shielf.Model.Book", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("shielf_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("shielf_whereid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("shielf_whereid");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("Shielf.Model.ShielfBook", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("count")
                        .HasColumnType("int");

                    b.Property<int>("max_year")
                        .HasColumnType("int");

                    b.Property<int>("min_year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("ShielfBook");
                });

            modelBuilder.Entity("Shielf.Model.Book", b =>
                {
                    b.HasOne("Shielf.Model.ShielfBook", "shielf_where")
                        .WithMany("books")
                        .HasForeignKey("shielf_whereid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("shielf_where");
                });

            modelBuilder.Entity("Shielf.Model.ShielfBook", b =>
                {
                    b.Navigation("books");
                });
#pragma warning restore 612, 618
        }
    }
}
